### ISSUE TITLE
Live ads not showing

### ISSUE THREAD

**Issue by siauderman** [ratson/cordova-plugin-admob-free#184]
Hi, I already put in a live ad code in the ID but my app still seems to show only test ads. Any idea why this could happen?

**Comment by ratson** [comment]
Could you try to run the example (https://github.com/ratson/cordova-plugin-admob-free/blob/master/examples/basic/www/js/index.js), replacing the ID with your own one, set `isTesting` to `false`, see if it works.

**Comment by tominou** [comment]
Also, you need to try on a release build (cordova build --release).

**Comment by aabdolla** [comment]
This just started happening to me two days ago. My app has been live for a month no problem and then with my latest release it has been saying Test Ad on top of my ads in production. I haven't touched the code that deals with ads since. I did update this plugin to take advantage of the new iPhone X fix.

**Comment by siauderman** [comment]
I did a release build, but it is not working. I don't know why.

**Comment by MBuchalik** [comment]
I am having the same issue. Test ads work fine, but production ones don't. One question: Does anybody of you have a live app in the App Store? I am wondering if the latest AdMob SDK maybe detects AdHoc builds and stops them from displaying ads. Maybe, ads will stark working again after you have published the app on the App Store?


To clarify why I am currently unable to debug this problem on my own:
As you might know, I have published a PR for the "forChild" problem. This fixed a few problems in my case. But unfortunately, after a week or so, ads suddenly stopped showing at all. In my case, I got probably banned from AdMob - even when trying one of the official AdMob test apps, ads won't show anymore. 
One of my clients reported that his ads don't show up as well. That's why I think that there is a problem with the latest SDK.

**Comment by josephharveyangeles** [comment]
I don't know if this will help, I'm using a different admob plugin: `cordova-admob-pro`, planning on switching to this one because yeah apparently that's not actually free, so I stumbled upon this project. But, the same issue is happening on `cordova-admob-pro`, test ads are showing, but on production ads are still test-ads, my app has been published for about a month now.

Looking into actual google admob sdk might be worth something.

Might be unrelated stupid question: admob has two id's `ca-app-pub-xxx~xxx` and `ca-app-pub-xxx/xxx`, examples are only using `ca-app-pub-xxx/xxx`, what's the purpose of the first one? Google Admob SDK uses the first one for initialization but I don't seem to see that in this plugin nor in `cordova-admob-pro`?

**Comment by bgosalci** [comment]
I have the same issue with cordova-admob-pro. The app version which is live, ads are working fine.
The new release that I'm working on, ads are not showing at all, even with isTest = true.

Whats even more frustrating that I cant find admob plugin that works. When using other plugins the app is not even building.

Has someone resolved this issue or found other plugin that works.

**Comment by bgosalci** [comment]
Hey @josephharveyangeles, which plugin did you use?

**Comment by josephharveyangeles** [comment]
@bgosalci I'm using this plugin. It didn't work the first time I switched from `cordova-admob-pro` didn't bother figuring out why. But I remember reinstalling all my cordova plugins again and creating a new ad unit on admob. Assets weren't probably thoroughly cleaned after removing `cordova-admob-pro` and then switching to this plugin. That's just my guess though.

**Comment by bgosalci** [comment]
@josephharveyangeles ok, cordova-plugin-admob-free won't compile for me. I get this error:
` cordova-generic-ad.jar does not exist in cordova-plugin-admob-free`

**Comment by josephharveyangeles** [comment]
@bgosalci try removing and adding the android platform again?

**Comment by arijitnaskar** [comment]
I am using the latest version of this plugin,  So I installed with ADMOB_APP_ID
`cordova plugin add cordova-plugin-admob-free --save --variable ADMOB_APP_ID="<YOUR_ADMOB_APP_ID_AS_FOUND_IN_ADMOB>"`
Its working with test Ad. But in production still its showing test ads.
Spent so much time on this. One thing I don't understant why the hell, test ad is showing. It could be no ad showing or somthing else. I have given my ad mob ad id, so there is no way of showing test ads.

**Comment by siauderman** [comment]
Hey I suggest you use cordova-admob-plus instead; that works. It's also by ratson.
https://github.com/admob-plus/admob-plus

**Comment by haresh14** [comment]
Hi All,
Does anyone got the solution for this issue? because i am facing the same issue.

**Comment by siauderman** [comment]
> 
> 
> Hi All,
> Does anyone got the solution for this issue? because i am facing the same issue.

> 
> 
> Hey I suggest you use cordova-admob-plus instead; that works. It's also by ratson.
> https://github.com/admob-plus/admob-plus

This is the solution.

**Comment by wackingninja** [comment]
check out this tutorial for cordova app development ads are working here

**Comment by wackingninja** [comment]
check out this tutorial for cordova app development ads are working here
https://www.youtube.com/playlist?list=PLOYvLvZ5tzBSGxKWIM7fwqVgKG6vLoVZ7
